use bevy::{
    prelude::{App, AssetServer, Plugin},
    tasks::IoTaskPool,
};

use crate::BevassetIo;

/// Bevy plugin that will insert a custom [`AssetServer`](bevy::asset::AssetServer)
/// instead of the default added by the [`AssetPlugin`](bevy::asset::AssetPlugin).
///
/// If you are using the [`DefaultPlugins`](bevy::prelude::DefaultPlugins) group from Bevy, it can be added this way:
///
/// ```rust
/// # use bevy::{prelude::*, asset::AssetPlugin};
/// # use bevasset_io::BevassetIoPlugin;
/// # fn main() {
///     App::new().add_plugins_with(DefaultPlugins, |group| {
///         group.add_before::<AssetPlugin, _>(BevassetIoPlugin::new(include_all_assets))
///     });
/// # }
/// # fn include_all_assets(#[allow(unused)] in_memory: &mut bevasset_io::BevassetIo){
/// # }
/// ```
///
/// The `include_all_assets` function must be generated by a build script (`build.rs`):
///
/// ```ignore
/// bevasset_io::generate_include_all_assets(
///     &Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap()).join("assets")
/// );
/// ```
///
/// and includeded in the source:
///
/// ```ignore
/// include!(concat!(env!("OUT_DIR"), "/include_all_assets.rs"));
/// ```
///
/// For the build script, use this dependency:
///
/// ```toml
/// [build-dependencies]
/// bevasset-io = { version = "*", features = ["build"] }
/// ```
#[derive(Debug)]
pub struct BevassetIoPlugin<F> {
    initializer: F,
}

impl<F> BevassetIoPlugin<F>
where
    F: Fn(&mut BevassetIo) + Send + Sync + 'static,
{
    /// Create a new instance of the plugin.
    pub fn new(asset_initializer: F) -> Self {
        Self {
            initializer: asset_initializer,
        }
    }
}

impl<F> Plugin for BevassetIoPlugin<F>
where
    F: Fn(&mut BevassetIo) + Send + Sync + 'static,
{
    fn build(&self, app: &mut App) {
        let task_pool = app
            .world
            .get_resource::<IoTaskPool>()
            .expect("`IoTaskPool` resource not found.")
            .0
            .clone();

        let mut bevasset_io = BevassetIo::new();
        let initializer = &self.initializer;
        initializer(&mut bevasset_io);

        app.insert_resource(AssetServer::new(bevasset_io, task_pool));
    }
}
